<?php

// -----------------------------------------
// semplice
// admin/atts/modules.php
// -----------------------------------------

// vp button options
$vp_button_options = get_vp_button_options(true);

$coverslider = array(
	'options' => array(
		'preview' => array(
			'title'  	 => 'Refresh',
			'hide-title' => true,
			'break'		 => '1',
			'posts' => array(
				'data-input-type' 	=> 'button',
				'title'		 		=> 'Preview',
				'help'				=> 'Please note that the drag and move (swipe) is only available in the frontend.',
				'button-title'		=> 'Refresh Preview',
				'size'		 		=> 'span4',
				'class'				=> 'semplice-button coverslider-preview admin-click-handler',
				'data-handler'		=> 'previewCoverslider',
			),
		),
		'posts' => array(
			'title'  	 => 'Posts',
			'hide-title' => true,
			'break'		 => '1',
			'posts' => array(
				'data-input-type' 	=> 'button',
				'title'		 		=> 'Add Covers',
				'help'				=> 'Please select the pages and projects to pull the fullscreen covers from.',
				'button-title'		=> 'Select Projects and Pages',
				'size'		 		=> 'span4',
				'class'				=> 'semplice-button white-button admin-click-handler',
				'data-handler'		=> 'addCovers',
			),
		),
		'main' => array(
			'title' 	 => 'Main Options',
			'hide-title' => true,
			'break'		 => '2,1,1,1',
			'navigation' => array(
				'data-input-type' 			=> 'switch',
				'switch-type'				=> 'twoway',
				'title'		 				=> 'Navigation',
				'size'		 				=> 'span2',
				'class'						=> 'listen-coverslider',
				'default' 	 				=> 'dots',
				'switch-values' => array(
					'dots'  		=> 'Dots',
					'arrows'	 	=> 'Arrows',
				),
			),
			'color' => array(
				'title'			=> 'Color',
				'size'			=> 'span2',
				'data-input-type'	=> 'color',
				'default'		=> 'transparent',
				'class'			=> 'color-picker admin-listen-handler',
				'data-picker'	=> 'coverSlider',
				'data-handler'  => 'colorPicker',
			),
			'orientation' => array(
				'data-input-type' 			=> 'switch',
				'switch-type'				=> 'twoway',
				'title'		 				=> 'Orientation',
				'size'		 				=> 'span4',
				'class'						=> 'listen-coverslider',
				'default' 	 				=> 'vertical',
				'switch-values' => array(
					'vertical'  		=> 'Vertical',
					'horizontal'	 	=> 'Horizontal',
				),
			),
			'content_after_slider' => array(
				'title'				 => 'Content after Slider',
				'help'				 => 'If you want to display a normal page after the cover slider you can select your page here.<br /><br /><b>Note:</b> This feature is only available for a horizontal cover slider and there will be no preview in the editor.',
				'size'				 => 'span4',
				'data-input-type'    => 'select-box',
				'class'			  	 => 'listen-coverslider',
				'default'			 => '1',
				'select-box-values' => semplice_get_post_dropdown('page'),
			),
		),
		'vp-button-switch' => array(
			'title'  	 => 'View Project Button',
			'break'		 => '1',
			'help'		 => 'Please note that this settings will be overwritten from individual customized \'View Project\' buttons.',
			'data-hide-mobile' => true,
			'vp_button_type' => array(
				'data-input-type' 			=> 'switch',
				'switch-type'				=> 'twoway',
				'title'		 				=> 'View Project Button',
				'hide-title'				=> true,
				'size'		 				=> 'span4',
				'data-visibility-switch' 	=> true,
				'data-visibility-values' 	=> 'default,custom',
				'data-visibility-prefix'	=> 'ov-vp-button',
				'default' 	 				=> 'default',
				'class'						=> 'listen-coverslider',
				'switch-values' => array(
					'default'  	=> 'Default',
					'custom'	=> 'Custom',
				),
			),
		),
		// coverslider view project button
		'vp-button-general' => $vp_button_options['general'],
		'vp-button-link'	=> $vp_button_options['link'],
		'vp-button-hover'	=> $vp_button_options['hover'],
	),
	'transitions' => array(
		'animation-options' => array(
			'title' 	 => 'Parallax',
			'hide-title' => true,
			'break'		 => '2,1',
			'easing' => array(
				'title'				 => 'Easing',
				'size'				 => 'span2',
				'data-input-type'    => 'select-box',
				'class'			  	 => 'listen-coverslider',
				'default'			 => 'ease',
				'select-box-values' => array(
					'ease'			=> 'ease (default)',
					'linear'		=> 'linear',
					'ease-in'		=> 'ease-in',
					'ease-out'		=> 'ease-out',
					'ease-in-out'	=> 'ease-in-out',
					'cubic-bezier(0.550, 0.085, 0.680, 0.530)' => 'easeInQuad',
					'cubic-bezier(0.250, 0.460, 0.450, 0.940)' => 'easeOutQuad',
					'cubic-bezier(0.455, 0.030, 0.515, 0.955)' => 'easeInOutQuad',
					'cubic-bezier(0.550, 0.055, 0.675, 0.190)' => 'easeInCubic',
					'cubic-bezier(0.215, 0.610, 0.355, 1.000)' => 'easeOutCubic',
					'cubic-bezier(0.645, 0.045, 0.355, 1.000)' => 'easeInOutCubic',
					'cubic-bezier(0.895, 0.030, 0.685, 0.220)' => 'easeInQuart',
					'cubic-bezier(0.165, 0.840, 0.440, 1.000)' => 'easeOutQuart',
					'cubic-bezier(0.770, 0.000, 0.175, 1.000)' => 'easeInOutQuart',
					'cubic-bezier(0.755, 0.050, 0.855, 0.060)' => 'easeInQuint',
					'cubic-bezier(0.230, 1.000, 0.320, 1.000)' => 'easeOutQuint',
					'cubic-bezier(0.860, 0.000, 0.070, 1.000)' => 'easeInOutQuint',
					'cubic-bezier(0.470, 0.000, 0.745, 0.715)' => 'easeInSine',
					'cubic-bezier(0.390, 0.575, 0.565, 1.000)' => 'easeOutSine',
					'cubic-bezier(0.445, 0.050, 0.550, 0.950)' => 'easeInOutSine',
					'cubic-bezier(0.950, 0.050, 0.795, 0.035)' => 'easeInExpo',
					'cubic-bezier(0.190, 1.000, 0.220, 1.000)' => 'easeOutExpo',
					'cubic-bezier(1.000, 0.000, 0.000, 1.000)' => 'easeInOutExpo',
					'cubic-bezier(0.600, 0.040, 0.980, 0.335)' => 'easeInCirc',
					'cubic-bezier(0.075, 0.820, 0.165, 1.000)' => 'easeOutCirc',
					'cubic-bezier(0.785, 0.135, 0.150, 0.860)' => 'easeInOutCirc',
					'cubic-bezier(0.600, -0.280, 0.735, 0.045)' => 'easeInBack',
					'cubic-bezier(0.175, 0.885, 0.320, 1.275)' => 'easeOutBack',
					'cubic-bezier(0.680, -0.550, 0.265, 1.550)' => 'easeInOutBack',
				),
			),
			'duration' => array(
				'title'				=> 'Duration',
				'size'				=> 'span2',
				'offset'			=> false,
				'data-input-type' 	=> 'range-slider',
				'class'				=> 'listen-coverslider',
				'default'			=> 900,
				'min'				=> 0,
				'max'				=> 9999,
				'data-range-slider' => 'coverSlider',
			),
			'custom_easing' => array(
				'data-input-type'	=> 'input-text',
				'title'		 	=> 'Custom Easing',
				'help'			=> 'Add your custom easing here.<br /><br /><b>Format:</b><br />cubic-bezier(0, 0, 0, 0)<br /><br /><b>Note:</b><br />This will overwrite the selected easing above unless its completely empty. You can create your own easing <a href="http://cubic-bezier.com" target="_blank">here</a>.',
				'size'		 	=> 'span4',
				'placeholder'	=> 'cubic-bezier(0, 0, 0, 0)',
				'default'		=> '',
				'class'			=> 'listen-coverslider',
			),
		),
		'parallax-options' => array(
			'title' 	 => 'Parallax',
			'break'		 => '1,2,2',
			'parallax' => array(
				'data-input-type' 			=> 'switch',
				'switch-type'				=> 'twoway',
				'title'		 				=> 'Parallax',
				'hide-title'				=> true,
				'size'		 				=> 'span4',
				'class'						=> 'listen-coverslider',
				'data-visibility-switch' 	=> true,
				'data-visibility-values' 	=> 'enabled,disabled',
				'data-visibility-prefix'	=> 'ov-cs-parallax',
				'default' 	 				=> 'disabled',
				'switch-values' => array(
					'enabled'  	=> 'Enabled',
					'disabled'	=> 'Disabled',
				),
			),
			'parallax_type' => array(
				'data-input-type' 			=> 'switch',
				'switch-type'				=> 'twoway',
				'title'		 				=> 'Type',
				'size'		 				=> 'span2',
				'class'						=> 'listen-coverslider',
				'style-class'				=> 'ov-cs-parallax-enabled',
				'default' 	 				=> 'cover',
				'switch-values' => array(
					'cover'  		=> 'Cover',
					'reveal'	 	=> 'Reveal',
				),
			),
			'parallax_offset' => array(
				'title'				=> 'Offset in %',
				'size'				=> 'span2',
				'offset'			=> false,
				'data-input-type' 	=> 'range-slider',
				'class'				=> 'listen-coverslider',
				'default'			=> 60,
				'min'				=> 0,
				'max'				=> 100,
				'style-class'		=> 'ov-cs-parallax-enabled',
				'data-range-slider' => 'coverSlider',
			),
		),
	),
);

?>