<?php

// -----------------------------------------
// semplice
// admin/atts/customize.php
// -----------------------------------------

$customize = array(

	// -----------------------------------------
	// grid
	// -----------------------------------------

	'grid' => array(
		'tabs' => array(
			'options' => array(
				'width-options' => array(
					'title'  	 => 'Grid',
					'break'		 => '1',
					'width' => array(
						'title'				=> 'Width',
						'help'				=> 'Important: If your grid width is bigger than your browser window the preview will not be displayed correctly. The minimum grid width is 1170px',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'grid-width admin-listen-handler',
						'data-handler'		=> 'gridSettings',
						'default'			=> 1170,
						'min'				=> 1170,
						'max'				=> 9999,
						'data-range-slider' => 'gridSettings',
					),
				),
				'gutter-options' => array(
					'title'  	 => 'Gutter Width',
					'break'		 => '2',
					'gutter' => array(
						'title'				=> 'Desktop',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'gridSettings',
						'default'			=> 30,
						'min'				=> 0,
						'max'				=> 100,
						'data-range-slider' => 'gridSettings',
					),
					'responsive_gutter' => array(
						'title'				=> 'Responsive',
						'help'				=> 'The responsive gutter is for all your mobile breakpoints starting from < 1170px. Note: There is no preview for the mobile gutter.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'gridSettings',
						'default'			=> 30,
						'min'				=> 0,
						'max'				=> 100,
						'data-range-slider' => 'gridSettings',
					),
				),
				'outer-padding' => array(
					'title'  	 => 'Outer Padding',
					'break'		 => '1',
					'outer_padding' => array(
						'title'				=> 'Desktop',
						'help'				=> 'To avoid that your grid sticks to the browser edges, there is always a outer padding on both sides of your grid.<br /><br />This setting only applies for the desktop breakpoint. On non-desktop and mobile breakpoints the outer padding will default to 30px (tablets) and 20px (mobile)<br /><br />Note: There is no preview for this setting and it will be only visible in the frontend.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'gridSettings',
						'default'			=> 30,
						'min'				=> 0,
						'max'				=> 9999,
						'data-range-slider' => 'gridSettings',
					),
				),
			),
		),
	),

	// -----------------------------------------
	// webfonts
	// -----------------------------------------

	'webfonts' => array(
		// add ressource
		'add-ressource' => array(
			'service' => array(
				'options' => array(
					'title' => 'options',
					'break' => '1,1',
					'hide-title' => true,
					'ressource-name' => array(
						'title'				=> 'Resource Name',
						'size'				=> 'span4-popup',
						'data-input-type'	=> 'input-text',
						'default'			=> '',
						'placeholder'		=> 'Example: Typekit, Fonts.com'
					),
					'ressource-src' => array(
						'title'				=> 'Embed Code',
						'size'				=> 'span4-popup',
						'data-input-type'	=> 'textarea',
						'default'			=> '',
						'placeholder'		=> 'Paste your CSS/JS code here',
						'class'				=> 'ressource-src',
						'help'				=> 'Please paste the embed code for your CSS / JS file in this field. Normally you will get this code in the public settings of your font kit.<br /><br /><b>Example for fonts.com:</b><br /><i>' . htmlentities('<link type="text/css" rel="stylesheet" href="http://fast.fonts.net/cssapi/xxx.css"/>') . '</i>',
					),
				),
			),
			'self-hosted' => array(
				'options' => array(
					'title' => 'options',
					'break' => '1,1',
					'hide-title' => true,
					'ressource-name' => array(
						'title'				=> 'Resource Name',
						'size'				=> 'span4-popup',
						'data-input-type'	=> 'input-text',
						'default'			=> '',
						'placeholder'		=> 'Example: Helvetica CSS'
					),
					'ressource-src' => array(
						'title'				=> 'Embed Code',
						'size'				=> 'span4-popup',
						'data-input-type'	=> 'textarea',
						'default'			=> '',
						'placeholder'		=> 'Paste your CSS code here',
						'class'				=> 'ressource-src',
						'help'				=> 'Please paste the css code for your self hosted webfonts here. Normally this code is shipped with your webfonts.<br /><br /><b>Example code:</b> <a class="help-link" href="https://pastebin.com/5anukcSG" target="_blank">Pastebin</a>',
					),
				),
			),
		),
		// add font
		'add-font' => array(
			'options' => array(
				'title' => 'options',
				'break' => '1,2,1,2',
				'hide-title' => true,
				'display-name' => array(
					'title'				=> 'Display Name',
					'size'				=> 'span4-popup',
					'data-input-type'	=> 'input-text',
					'default'			=> '',
					'placeholder'		=> 'Helvetica Bold',
					'class'				=> 'is-font-setting',
					'help'				=> 'This name gets displayed in font select dropdowns. The name is up to you but it\'s there to help you find and select your font later.<br /><br /><b>Example</b><br />Helvetica Bold'
				),
				'system-name' => array(
					'title'				=> 'System Name',
					'size'				=> 'span2-popup',
					'data-input-type'	=> 'input-text',
					'default'			=> '',
					'placeholder'		=> 'minion-pro-bold',
					'class'				=> 'is-font-setting',
					'help'				=> 'This is the \'real\' font name which is registered by your font files. You can get the real fontname from your font kit export settings (service) or in your self hosted css assets. (self hosted)',
				),
				'font-weight' => array(
					'title'				=> 'Font Weight',
					'size'				=> 'span2-popup',
					'data-input-type'	=> 'select-box',
					'default'			=> '400',
					'class'				=> 'is-font-setting',
					'help'				=> 'Select the font weight of your font. Normally your font service provides you with the correct font-weight values.<br /><br />If your fontname includes the font weight like in \'HelveticaNeueBold\' you can ignore this setting and just set \'Font Weight Usage\' to \'Via Fontname\'',
					'select-box-values' => array(
						100 => '100',
						200 => '200',
						300 => '300',
						400 => '400',
						500 => '500',
						600 => '600',
						700 => '700',
						800 => '800',
						900 => '900',
					),
				),
				'font-weight-usage' => array(
					'title'		 => 'Font Weight usage',
					'size'		 => 'span4-popup',
					'data-input-type' => 'switch',
					'switch-type'=> 'twoway',
					'class' 	 => 'admin-switch',
					'default' 	 => 'css',
					'class'				=> 'is-font-setting',
					'help'				=> 'If your fontname includes the font weight like in \'HelveticaNeueBold\' please set this setting to \'Via Fontname\'. If you have to define a numeric font weight please leave it to \'Via CSS\'',
					'switch-values' => array(
						'css'	=> 'Via CSS',
						'fontname' => 'Via Fontname',
					),
				),
				'category' => array(
					'title'		 => 'Category',
					'size'		 => 'span2-popup',
					'data-input-type' => 'switch',
					'switch-type'=> 'twoway',
					'class' 	 => 'admin-switch',
					'default' 	 => 'sans-serif',
					'class'				=> 'is-font-setting',
					'switch-values' => array(
						'sans-serif'	=> 'Sans-Serif',
						'serif' => 'Serif',
					),
				),
				'font-style' => array(
					'title'		 => 'Font Style',
					'size'		 => 'span2-popup',
					'data-input-type' => 'switch',
					'switch-type'=> 'twoway',
					'class' 	 => 'admin-switch',
					'default' 	 => 'normal',
					'class'				=> 'is-font-setting',
					'switch-values' => array(
						'normal'	=> 'Normal',
						'italic' => 'Italic',
					),
				),
			),
		),
	),

	// -----------------------------------------
	// navigations
	// -----------------------------------------

	'navigation' => array(
		'tabs' => array(
			'styling' => array(
				'general_options' => array(
					'title' => 'Name your Navigation',
					'break' => '1,1,1',
					'hide-title' => false,
					'name' => array(
						'title'				=> 'Name',
						'hide-title'		=> true,
						'size'				=> 'span4',
						'data-input-type'	=> 'input-text',
						'default'			=> '',
						'placeholder'		=> 'My Nav',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'navigations',
						'data-target'		=> 'none',
					),
					'default' => array(
						'data-input-type' 	=> 'button',
						'title'		 		=> 'Default',
						'button-title'		=> 'Set as default',
						'help'				=> 'You can set this navigation as your global default whenever you create a new page or project.<br /><br />Note that this will not overwrite the navigations you selected in the page settings for your individual pages and projects.',
						'size'		 		=> 'span4',
						'class'				=> 'semplice-button navbar-default white-button',
					),
				),
				'logo_options' => array(
					'title' => 'Logo options',
					'break' => '1,2,2,2,2,1,1',
					'hide-title' => false,
					'logo_type' => array(
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Logo Type',
						'size'		 				=> 'span4',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'navigations',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'img,text',
						'data-visibility-prefix'	=> 'ov-logo',
						'default' 	 				=> 'text',
						'switch-values' => array(
							'text'  	=> 'Textlogo',
							'img'	 	=> 'Image',
						),
					),
					'logo_text' => array(
						'title'				=> 'Textlogo',
						'size'				=> 'span2',
						'data-input-type'	=> 'input-text',
						'default'			=> get_bloginfo('name'),
						'placeholder'		=> 'My Textlogo',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'navigations',
						'style-class'		=> 'ov-logo-text',
					),
					'logo_text_color' => array(
						'title'			=> 'Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '.logo a',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-css-attribute'=> 'color',
						'style-class'		=> 'ov-logo-text',
						'data-picker'		=> 'navigations',
					),
					'logo_text_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'data-target'		=> '.logo a',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'style-class'		=> 'ov-logo-text',
						'select-box-values' => $fonts,
					),
					'logo_text_text_transform' => array(
						'title'				=> 'Text Transform',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'default'			=> 'none',
						'style-class'		=> 'ov-logo-text',
						'data-target'		=> '.logo a',
						'data-css-attribute'=> 'text-transform',
						'select-box-values' => array(
							'none'			=> 'None',
							'uppercase'		=> 'Uppercase',
						),
					),
					'logo_text_fontsize' => array(
						'title'				=> 'Fontsize',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'style-class'		=> 'ov-logo-text',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.logo a',
						'data-has-unit'		=> true,
						'default'			=> 22,
						'min'				=> 0,
						'max'				=> 9999,
						'data-range-slider' => 'navigations',
					),
					'logo_text_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-logo-text',
						'data-target'		=> '.logo a',
						'data-css-attribute'=> 'letter-spacing',
						'data-divider'		=> 10,
						'data-has-unit'		=> true,
						'data-negative' 	=> true,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'data-range-slider' => 'navigations',
					),
					'logo_img' => array(
						'title'				=> 'Upload',
						'help'				=> 'Please note that on many servers due to security reasons you can\'t upload an svg. If you can\'t upload an svg image please use the \'SVG Code\' field below.',
						'size'				=> 'span2',
						'data-input-type'	=> 'admin-image-upload',
						'data-target'		=> '.content-block',
						'default'			=> '',
						'class'				=> 'admin-listen-handler',
						'style-class'		=> 'ov-logo-img',
						'data-handler'		=> 'navigations',
						'data-upload'		=> 'logoImg',
					),
					'logo_img_width' => array(
						'title'				=> 'Width',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 100,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-css-attribute'=> 'width',
						'data-target'		=> '.logo img, .logo svg',
						'style-class'		=> 'ov-logo-img',
						'data-range-slider' => 'navigations',
					),
					'logo_svg' => array(
						'title'				=> 'SVG Code',
						'size'				=> 'span4',
						'help'				=> 'In order to see your SVG Image please make sure that there is no logo image uploaded above. (because that will be displayed instead)',
						'data-input-type'	=> 'codemirror',
						'data-target'		=> '.content-block',
						'placeholder'		=> '<!-- Please paste your svg code here. Example: <svg>...</svg> -->',
						'default'			=> '',
						'button-title'		=> 'SVG Code',
						'class'				=> 'semplice-button codemirror white-button admin-click-handler',
						'style-class'		=> 'ov-logo-img',
						'data-handler'		=> 'codemirror',
					),
					'logo_padding_left' => array(
						'title'				=> 'Logo Padding Left',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '.logo',
						'data-css-attribute'=> 'padding-left',
						'default'			=> 40,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'logo_padding_right' => array(
						'title'				=> 'Logo Padding Right',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '.logo',
						'data-css-attribute'=> 'padding-right',
						'default'			=> 40,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'logo_margin_bottom' => array(
						'title'				=> 'Logo Bottom Margin',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '.logo',
						'data-css-attribute'=> 'margin-bottom',
						'default'			=> 20,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'logo_alignment' => array(
						'title'				=> 'Alignment',
						'size'				=> 'span4',
						'data-input-type'	=> 'select-box',
						'data-target'		=> '.logo',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'data-css-attribute'=> 'align-items',
						'data-target'		=> '.logo',
						'help'				=> 'This setting is has no effect on some navigations.',
						'select-box-values' => array(
							'center'	 => 'Middle',
							'flex-start' => 'Top',
						),
					),
				),
				'navigation_bar' => array(
					'title' => 'Navigation Bar',
					'break' => '2,2,2,1,1',
					'hide-title' => false,
					'navbar_type' => array(
						'data-input-type' 			=> 'switch',
						'help'						=> 'For certain navigations (for example centered ones) this setting is irrelevant.',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Width',
						'size'		 				=> 'span2',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'navigations',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'container,container-fluid',
						'data-visibility-prefix'	=> 'ov-navwidth',
						'default' 	 				=> 'container',
						'switch-values' => array(
							'container'  		=> 'Grid',
							'container-fluid'	=> 'Fluid',
						),
					),
					'navbar_mode' => array(
						'data-input-type' 			=> 'switch',
						'help'						=> 'Select if you want your Navigation Bar to stay sticky or not.',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Mode',
						'size'		 				=> 'span2',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'navigations',
						'data-target'				=> 'none',
						'default' 	 				=> 'sticky',
						'switch-values' => array(
							'sticky'  	=> 'Sticky',
							'normal'	=> 'Normal',
						),
					),
					'navbar_padding' => array(
						'title'				=> 'Horizontal Padding',
						'help'				=> 'If you have a centered menu and logo this setting is still viable for the mobile hamburger fallback.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '.navbar-left',
						'data-css-attribute'=> 'left',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'style-class'		=> 'ov-navwidth-container-fluid',
						'data-range-slider' => 'navigations',
					),
					'navbar_padding_vertical' => array(
						'title'				=> 'Padding Ver',
						'help'				=> 'If you have a top aligned logo and menu you can add spacing with this option.<br /><br />Please note that if you use this settings its recommended to have a transparent navbar background.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '.semplice-navbar',
						'data-css-attribute'=> 'padding',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'navbar_height' => array(
						'title'				=> 'Height',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '.semplice-navbar',
						'data-css-attribute'=> 'height',
						'default'			=> 70,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'navbar_bg_color' => array(
						'title'			=> 'Background',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '.semplice-navbar',
						'data-css-attribute' => 'background-color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-picker'		=> 'navigations',
					),
					'navbar_bg_opacity' => array(
						'title'				=> 'BG Opacity',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'min'				=> 0,
						'max'				=> 100,
						'default'			=> 100,
						'data-divider'		=> 100,
						'data-range-slider' => 'navigations',
					),
					'navbar_cover_transparent' => array(
						'title'				=> 'Transparent while in Cover',
						'help'				=> 'Enabled your navbar background will be transparent while above the cover image or video. After scrolling out of the cover your defined background-color will fade in.<br /><br /><b>Note:</b> You can add a \'Cover\' in the editor by clicking on \'Cover\' and then enable it.',
						'data-input-type' 	=> 'switch',
						'switch-type'		=> 'twoway',
						'size'				=> 'span4',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'default'			=> 'disabled',
						'data-target'		=> 'none',
						'switch-values' => array(
							'disabled'		=> 'Disabled',
							'enabled'		=> 'Enabled'
						),
					),
					'navbar_bg_visibility_overlay' => array(
						'title'				=> 'Background Visibility in Overlay',
						'help'				=> 'Select \'hidden\' if you want to hide the navbar background while the overlay is open.',
						'data-input-type' 	=> 'switch',
						'switch-type'		=> 'twoway',
						'size'				=> 'span4',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'default'			=> 'visible',
						'data-target'		=> 'none',
						'switch-values' => array(
							'visible'		=> 'Visible',
							'hidden'		=> 'Hidden'
						),
					),
					/*
					'preset' => array(
						'data-input-type' 	=> 'button',
						'title'		 		=> 'Navigation Preset',
						'button-title'		=> 'Change Preset',
						'size'		 		=> 'span4',
						'class'				=> 'white-button semplice-button admin-listen-handler',
						'data-handler'		=> 'navigations', 
					),
					*/
				),
			),

			'menu' => array(
				'edit_menu' => array(
					'title' => 'Edit Menu',
					'break' => '1',
					'hide-title' => false,
					'categories' => array(
						'data-input-type' 	=> 'button',
						'hide-title'		=> true,
						'title'		 		=> 'Edit Menu Items',
						'button-title'		=> 'Edit Menu Items',
						'size'		 		=> 'span4',
						'class'				=> 'semplice-button admin-click-handler',
						'data-handler'		=> 'editMenu',
					),
				),
				'menu_options' => array(
					'title' => 'Menu Options',
					'break' => '1,2,2,2,2,2,2,2,1',
					'hide-title' => false,
					'menu_type' => array(
						'help'						=> 'Please go to the tab \'Overlay/Mobile\' to customize the hamburger icon.',
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Type',
						'size'		 				=> 'span4',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'navigations',
						'default' 	 				=> 'text',
						'data-target'				=> 'none',
						'switch-values' => array(
								'text'  		=> 'Text',
							'hamburger'	 	=> 'Hamburger',
						),
					),
					'menu_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'data-target'		=> 'nav.standard',
						'select-box-values' => $fonts,
					),
					'menu_fontsize' => array(
						'title'				=> 'Fontsize',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 15,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-target'		=> '.semplice-navbar li a span',
						'data-css-attribute'=> 'font-size',
						'data-range-slider' => 'navigations',
					),
					'menu_color' => array(
						'title'			=> 'Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-target'		=> '.semplice-navbar li a span',
						'data-css-attribute'=> 'color',
						'data-picker'		=> 'navigations',
					),
					'menu_padding' => array(
						'title'				=> 'Items Padding',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'data-target'		=> '.semplice-navbar li a',
						'data-css-attribute'=> 'padding-right',
						'default'			=> 30,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'menu_text_transform' => array(
						'title'				=> 'Text Transform',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'default'			=> 'none',
						'style-class'		=> 'ov-menu-text',
						'data-target'		=> '.semplice-navbar li a span',
						'data-css-attribute'=> 'text-transform',
						'select-box-values' => array(
							'none'			=> 'None',
							'uppercase'		=> 'Uppercase',
						),
					),
					'menu_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-divider'		=> 10,
						'data-has-unit'		=> true,
						'data-negative' 	=> true,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'data-target'		=> '.semplice-navbar li a span',
						'data-css-attribute'=> 'letter-spacing',
						'data-range-slider' => 'navigations',
					),
					'menu_border_color' => array(
						'title'			=> 'Underline Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> '#000000',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-target'		=> 'li a span',
						'data-css-attribute'=> 'border-bottom-color',
						'data-picker'		=> 'navigations',
					),
					'menu_border' => array(
						'title'				=> 'Underline',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 1000,
						'data-has-unit'		=> true,
						'data-target'		=> '.semplice-navbar li a span',
						'data-css-attribute'=> 'border-bottom-width',
						'data-range-slider' => 'navigations',
					),
					'menu_border_padding' => array(
						'title'				=> 'Underline Padding',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 1000,
						'data-has-unit'		=> true,
						'data-target'		=> '.semplice-navbar li a span',
						'data-css-attribute'=> 'padding-bottom',
						'data-range-slider' => 'navigations',
					),
					'menu_alignment' => array(
						'title'				=> 'Alignment',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'data-target'		=> 'nav.standard ul',
						'data-css-attribute'=> 'align-items',
						'help'				=> 'Some navigations have a fixed alignment so that this setting has no effect.',
						'select-box-values' => array(
							'center'	 => 'Middle',
							'flex-start' => 'Top',
						),
					),
					'menu_mobile_fallback' => array(
						'help'						=> 'Select \'Disabled\' if you want to disable the mobile fallback (hamburger) and show your menu instead',
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Mobile Hamburger Fallback',
						'size'		 				=> 'span4',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'navigations',
						'default' 	 				=> 'enabled',
						'data-target'				=> 'none',
						'switch-values' => array(
							'enabled'	 	=> 'Enabled',
							'disabled'  	=> 'Disabled',
						),
					),
				),
				'mouseover_options' => array(
					'title' => 'Mouseover Options',
					'break' => '2',
					'hide-title' => false,
					'style-class'	=> 'ov-menu-text',
					'help'			=> 'The mouseover color will be also the color of your active link.',
					'menu_mouseover_color' => array(
						'title'			=> 'TextColor',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'style-class'	=> 'ov-menu-text',
						'data-target'	=> 'mouseover',
						'data-picker'		=> 'navigations',
					),
					'menu_border_mouseover_color' => array(
						'title'			=> 'Border Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'style-class'	=> 'ov-menu-text',
						'data-target'	=> 'mouseover',
						'data-picker'		=> 'navigations',
					),
				),
			),
			'overlay' => array(
				'hamburger_options' => array(
					'title' => 'Hamburger',
					'break' => '2,2,1',
					'hide-title' => false,
					'hamburger_color' => array(
						'title'			=> 'Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-target'		=> '.open-menu span',
						'data-css-attribute'=> 'background-color',
						'data-picker'		=> 'navigations',
					),
					'hamburger_width' => array(
						'title'				=> 'Width',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 24,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'hamburger_thickness' => array(
						'title'				=> 'Thickness',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 2,
						'min'				=> 0,
						'max'				=> 9999,
						'data-target'		=> '.open-menu span',
						'data-css-attribute'=> 'height',
						'data-range-slider' => 'navigations',
					),
					'hamburger_padding' => array(
						'title'				=> 'Padding',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 6,
						'min'				=> 0,
						'max'				=> 9999,
						'data-range-slider' => 'navigations',
					),
					'hamburger_alignment' => array(
						'title'				=> 'Alignment',
						'size'				=> 'span4',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'data-css-attribute'=> 'align-items',
						'data-target'		=> '.hamburger',
						'help'				=> 'This setting is has no effect on some navigations.',
						'select-box-values' => array(
							'center'	 => 'Middle',
							'flex-start' => 'Top',
						),
					),
				),
				'overlay_options' => array(
					'title' => 'Overlay Menu',
					'break' => '1,2,2,2,2,2,2,2,2,2',
					'hide-title' => false,
					'overlay_type' => array(
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Width',
						'size'		 				=> 'span4',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'navigations',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'container,container-fluid',
						'data-visibility-prefix'	=> 'ov-overlaywidth',
						'default' 	 				=> 'container',
						'data-target'				=> 'none',
						'switch-values' => array(
							'container'  		=> 'Grid',
							'container-fluid'	=> 'Fluid',
						),
					),
					'overlay_bg_color' => array(
						'title'			=> 'Background',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-picker'	=> 'navigations',
					),
					'overlay_bg_opacity' => array(
						'title'				=> 'BG Opacity',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'min'				=> 0,
						'max'				=> 100,
						'default'			=> 100,
						'data-divider'		=> 100,
						'data-range-slider' => 'navigations',
					),
					'overlay_padding_left' => array(
						'title'				=> 'Padding Left',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'left',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'style-class'		=> 'ov-overlaywidth-container-fluid',
						'data-range-slider' => 'navigations',
					),
					'overlay_padding_right' => array(
						'title'				=> 'Padding Right',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'right',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'style-class'		=> 'ov-overlaywidth-container-fluid',
						'data-range-slider' => 'navigations',
					),
					'overlay_padding_top' => array(
						'title'				=> 'Padding Top',
						'help'				=> 'Please note that the top padding for the menu only gets applied if your vertical alignment for the menu is set to \'Top\'',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'data-handler'		=> 'navigations',
						'class'				=> 'admin-listen-handler',
						'data-target'		=> '#overlay-menu nav',
						'data-css-attribute'=> 'padding-top',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-range-slider' => 'navigations',
					),
					'overlay_alignment_ver' => array(
						'title'				=> 'Alignment Ver',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'data-target'		=> '.overlay-menu-inner',
						'data-default'		=> 'middle',
						'select-box-values' => array(
							'align-middle'	=> 'Middle',
							'align-top'		=> 'Top',
						),
					),
					'overlay_alignment_hor' => array(
						'title'				=> 'Alignment Hor',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'data-target'		=> '#overlay-menu nav',
						'data-css-attribute'=> 'text-align',
						'select-box-values' => array(
							'center'	 => 'Center',
							'left' => 'Left',
							'right'	 => 'Right'
						),
					),
					'overlay_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'data-target'		=> '.overlay-nav',
						'select-box-values' => $fonts,
					),
					'overlay_fontsize' => array(
						'title'				=> 'Fontsize',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 32,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'font-size',
						'data-range-slider' => 'navigations',
					),
					'overlay_color' => array(
						'title'			=> 'Link Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'color',
						'data-picker'		=> 'navigations',
					),
					'overlay_padding' => array(
						'title'				=> 'Items Padding',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 20,
						'min'				=> 0,
						'max'				=> 9999,
						'data-has-unit'		=> true,
						'data-target'		=> '#overlay-menu li a',
						'data-css-attribute'=> 'padding-bottom',
						'data-range-slider' => 'navigations',
					),
					'overlay_text_transform' => array(
						'title'				=> 'Text Transform',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'navigations',
						'default'			=> 'none',
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'text-transform',
						'select-box-values' => array(
							'none'			=> 'None',
							'uppercase'		=> 'Uppercase',
						),
					),
					'overlay_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-divider'		=> 10,
						'data-has-unit'		=> true,
						'data-negative' 	=> true,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'letter-spacing',
						'data-range-slider' => 'navigations',
					),
					'overlay_border_color' => array(
						'title'			=> 'Underline Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> '#000000',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'border-bottom-color',
						'data-picker'		=> 'navigations',
					),
					'overlay_border' => array(
						'title'				=> 'Underline',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 1000,
						'data-has-unit'		=> true,
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'border-bottom-width',
						'data-range-slider' => 'navigations',
					),
					'overlay_border_padding' => array(
						'title'				=> 'Underline Padding',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'logo-font-size admin-listen-handler',
						'data-handler'		=> 'navigations',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 1000,
						'data-has-unit'		=> true,
						'data-target'		=> '#overlay-menu li a span',
						'data-css-attribute'=> 'padding-bottom',
						'data-range-slider' => 'navigations',
					),
				),
				'overlay_mouseover_options' => array(
					'title' => 'Mouseover Options',
					'break' => '2',
					'hide-title' => false,
					'help'			=> 'The mouseover color will be also the color of your active link.',
					'overlay_mouseover_color' => array(
						'title'			=> 'TextColor',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-target'	=> 'mouseover',
						'data-picker'	=> 'navigations',
					),
					'overlay_border_mouseover_color' => array(
						'title'			=> 'Border Color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-target'	=> 'mouseover',
						'data-picker'	=> 'navigations',
					),
				),
			),
		),
	),

	// -----------------------------------------
	// typography
	// -----------------------------------------

	'typography' => array(
		'tabs' => array(
			'heading' => array(
				'h1_switch' => array(
					'title' => 'Customize Headings',
					'break' => '1',
					'class'	=> 'add-effects-heading',
					'h1_customize' => array(
						'data-input-type' => 'onoff-switch',
						'style-class'=> 'first-switch',
						'title'		 => 'H1 Heading',
						'hide-title' => true,
						'size'		 => 'span4',
						'data-handler'  	=> 'typography',
						'class'		 => 'admin-listen-handler',
						'default' 	 => 'off',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'on,off',
						'data-visibility-prefix'	=> 'ov-h1',
						'switch-values' => array(
							'on'	 => 'On',
							'off'	 => 'Off',
						),
					),
				),
				'h1' => array(
					'title' => 'H1 Options',
					'break' => '2,2',
					'hide-title' => true,
					'class'			=> 'motion-sub',
					'h1_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'typography',
						'data-target'		=> '.preview-h1',
						'style-class'		=> 'ov-h1-on',
						'select-box-values' => $fonts,
					),
					'h1_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.preview-h1',
						'data-has-unit'		=> true,
						'default'			=> 42,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h1-on',
						'data-range-slider' => 'typography',
					),
					'h1_line_height' => array(
						'title'				=> 'Line height',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'line-height',
						'data-target'		=> '.preview-h1',
						'data-has-unit'		=> true,
						'default'			=> 54,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h1-on',
						'data-range-slider' => 'typography',
					),
					'h1_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'letter-spacing',
						'data-target'		=> '.preview-h1',
						'data-has-unit'		=> true,
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-negative' 	=> true,
						'data-divider'		=> 10,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'style-class'		=> 'ov-h1-on',
						'data-range-slider' => 'typography',
					),
				),
				'h2_switch' => array(
					'title' => 'Enable Options',
					'break' => '1',
					'hide-title' => true,
					'h2_customize' => array(
						'data-input-type' => 'onoff-switch',
						'title'		 => 'H2 Heading',
						'hide-title' => true,
						'size'		 => 'span4',
						'data-handler'  	=> 'typography',
						'class'		 => 'admin-listen-handler',
						'default' 	 => 'off',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'on,off',
						'data-visibility-prefix'	=> 'ov-h2',
						'switch-values' => array(
							'on'	 => 'On',
							'off'	 => 'Off',
						),
					),
				),
				'h2' => array(
					'title' => 'H2 Options',
					'break' => '2,2',
					'hide-title' => true,
					'class'	=> 'motion-sub',
					'h2_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'typography',
						'data-target'		=> '.preview-h2',
						'style-class'		=> 'ov-h2-on',
						'select-box-values' => $fonts,
					),
					'h2_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.preview-h2',
						'data-has-unit'		=> true,
						'default'			=> 36,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h2-on',
						'data-range-slider' => 'typography',
					),
					'h2_line_height' => array(
						'title'				=> 'Line height',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'line-height',
						'data-target'		=> '.preview-h2',
						'data-has-unit'		=> true,
						'default'			=> 48,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h2-on',
						'data-range-slider' => 'typography',
					),
					'h2_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'letter-spacing',
						'data-target'		=> '.preview-h2',
						'data-has-unit'		=> true,
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-negative' 	=> true,
						'data-divider'		=> 10,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'style-class'		=> 'ov-h2-on',
						'data-range-slider' => 'typography',
					),
				),
				'h3_switch' => array(
					'title' => 'Enable Options',
					'break' => '1',
					'hide-title' => true,
					'h3_customize' => array(
						'data-input-type' => 'onoff-switch',
						'title'		 => 'H3 Heading',
						'hide-title' => true,
						'size'		 => 'span4',
						'data-handler'  	=> 'typography',
						'class'		 => 'admin-listen-handler',
						'default' 	 => 'off',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'on,off',
						'data-visibility-prefix'	=> 'ov-h3',
						'switch-values' => array(
							'on'	 => 'On',
							'off'	 => 'Off',
						),
					),
				),
				'h3' => array(
					'title' => 'H3 Options',
					'break' => '2,2',
					'hide-title' => true,
					'class'	=> 'motion-sub',
					'h3_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'typography',
						'data-target'		=> '.preview-h3',
						'style-class'		=> 'ov-h3-on',
						'select-box-values' => $fonts,
					),
					'h3_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.preview-h3',
						'data-has-unit'		=> true,
						'default'			=> 28,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h3-on',
						'data-range-slider' => 'typography',
					),
					'h3_line_height' => array(
						'title'				=> 'Line height',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'line-height',
						'data-target'		=> '.preview-h3',
						'data-has-unit'		=> true,
						'default'			=> 40,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h3-on',
						'data-range-slider' => 'typography',
					),
					'h3_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'letter-spacing',
						'data-target'		=> '.preview-h3',
						'data-has-unit'		=> true,
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-negative' 	=> true,
						'data-divider'		=> 10,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'style-class'		=> 'ov-h3-on',
						'data-range-slider' => 'typography',
					),
				),
				'h4_switch' => array(
					'title' => 'Enable Options',
					'break' => '1',
					'hide-title' => true,
					'h4_customize' => array(
						'data-input-type' => 'onoff-switch',
						'title'		 => 'H4 Heading',
						'hide-title' => true,
						'size'		 => 'span4',
						'data-handler'  	=> 'typography',
						'class'		 => 'admin-listen-handler',
						'default' 	 => 'off',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'on,off',
						'data-visibility-prefix'	=> 'ov-h4',
						'switch-values' => array(
							'on'	 => 'On',
							'off'	 => 'Off',
						),
					),
				),
				'h4' => array(
					'title' => 'H4 Options',
					'break' => '2,2',
					'hide-title' => true,
					'class' => 'motion-sub',
					'h4_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'typography',
						'data-target'		=> '.preview-h4',
						'style-class'		=> 'ov-h4-on',
						'select-box-values' => $fonts,
					),
					'h4_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.preview-h4',
						'data-has-unit'		=> true,
						'default'			=> 24,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h4-on',
						'data-range-slider' => 'typography',
					),
					'h4_line_height' => array(
						'title'				=> 'Line height',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'line-height',
						'data-target'		=> '.preview-h4',
						'data-has-unit'		=> true,
						'default'			=> 36,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h4-on',
						'data-range-slider' => 'typography',
					),
					'h4_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'letter-spacing',
						'data-target'		=> '.preview-h4',
						'data-has-unit'		=> true,
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-negative' 	=> true,
						'data-divider'		=> 10,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'style-class'		=> 'ov-h4-on',
						'data-range-slider' => 'typography',
					),
				),
				'h5_switch' => array(
					'title' => 'Enable Options',
					'break' => '1',
					'hide-title' => true,
					'h5_customize' => array(
						'data-input-type' => 'onoff-switch',
						'title'		 => 'H5 Heading',
						'hide-title' => true,
						'size'		 => 'span4',
						'data-handler'  	=> 'typography',
						'class'		 => 'admin-listen-handler',
						'default' 	 => 'off',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'on,off',
						'data-visibility-prefix'	=> 'ov-h5',
						'switch-values' => array(
							'on'	 => 'On',
							'off'	 => 'Off',
						),
					),
				),
				'h5' => array(
					'title' => 'H5 Options',
					'break' => '2,2',
					'hide-title' => true,
					'class'	=> 'motion-sub',
					'h5_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'typography',
						'data-target'		=> '.preview-h5',
						'style-class'		=> 'ov-h5-on',
						'select-box-values' => $fonts,
					),
					'h5_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.preview-h5',
						'data-has-unit'		=> true,
						'default'			=> 20,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h5-on',
						'data-range-slider' => 'typography',
					),
					'h5_line_height' => array(
						'title'				=> 'Line height',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'line-height',
						'data-target'		=> '.preview-h5',
						'data-has-unit'		=> true,
						'default'			=> 32,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h5-on',
						'data-range-slider' => 'typography',
					),
					'h5_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'letter-spacing',
						'data-target'		=> '.preview-h5',
						'data-has-unit'		=> true,
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-negative' 	=> true,
						'data-divider'		=> 10,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'style-class'		=> 'ov-h5-on',
						'data-range-slider' => 'typography',
					),
				),
				'h6_switch' => array(
					'title' => 'Enable Options',
					'break' => '1',
					'hide-title' => true,
					'h6_customize' => array(
						'data-input-type' => 'onoff-switch',
						'title'		 => 'H6 Heading',
						'hide-title' => true,
						'size'		 => 'span4',
						'data-handler'  	=> 'typography',
						'class'		 => 'admin-listen-handler',
						'default' 	 => 'off',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'on,off',
						'data-visibility-prefix'	=> 'ov-h6',
						'switch-values' => array(
							'on'	 => 'On',
							'off'	 => 'Off',
						),
					),
				),
				'h6' => array(
					'title' => 'H6 Options',
					'break' => '2,2',
					'hide-title' => true,
					'class'	=> 'motion-sub',
					'h6_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'typography',
						'data-target'		=> '.preview-h6',
						'style-class'		=> 'ov-h6-on',
						'select-box-values' => $fonts,
					),
					'h6_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.preview-h6',
						'data-has-unit'		=> true,
						'default'			=> 18,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h6-on',
						'data-range-slider' => 'typography',
					),
					'h6_line_height' => array(
						'title'				=> 'Line height',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'line-height',
						'data-target'		=> '.preview-h6',
						'data-has-unit'		=> true,
						'default'			=> 30,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-h6-on',
						'data-range-slider' => 'typography',
					),
					'h6_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'letter-spacing',
						'data-target'		=> '.preview-h6',
						'data-has-unit'		=> true,
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-negative' 	=> true,
						'data-divider'		=> 10,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'style-class'		=> 'ov-h6-on',
						'data-range-slider' => 'typography',
					),
				),
			),
			'paragraph' => array(
				'p' => array(
					'title' => 'paragraph Options',
					'break' => '2,2',
					'hide-title' => true,
					'p_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'typography',
						'data-target'		=> '.preview-paragraph',
						'style-class'		=> 'ov-paragraph-on',
						'select-box-values' => $fonts,
					),
					'p_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.preview-paragraph',
						'data-has-unit'		=> true,
						'default'			=> 18,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-paragraph-on',
						'data-range-slider' => 'typography',
					),
					'p_line_height' => array(
						'title'				=> 'Line height',
						'help'				=> 'Please note that this is a relative line height based on the calculation: <br/><br /><i>{ line height / 18 (base font size) }</i>.<br /><br /><b>Example</b><br />Your line height: 36<br />Divided by: 18<br />Result: 2.<br /><br />That means your line-height is 2 times your fontsize.<br /><br />In this Example if your font size is 20px, your line height would be 2 * 20 = 40px.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'line-height',
						'data-target'		=> '.preview-paragraph',
						'data-divider'	    => 18,
						'default'			=> 30,
						'min'				=> 0,
						'max'				=> 9999,
						'style-class'		=> 'ov-paragraph-on',
						'data-range-slider' => 'typography',
					),
					'p_letter_spacing' => array(
						'title'				=> 'Letter Spacing',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'typography',
						'data-css-attribute'=> 'letter-spacing',
						'data-target'		=> '.preview-paragraph',
						'data-has-unit'		=> true,
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-negative' 	=> true,
						'data-divider'		=> 10,
						'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
						'style-class'		=> 'ov-paragraph-on',
						'data-range-slider' => 'typography',
					),
				),
			)
		),
	),

	// -----------------------------------------
	// thumbhover
	// -----------------------------------------

	'thumbhover' => array(
		'tabs' => array(
			'options' => array(
				'thumb-hover-scale' => get_thumb_hover_options('scale', $fonts),
				'thumb-hover-background' => get_thumb_hover_options('background', $fonts),
				'thumb-hover-title-category' => get_thumb_hover_options('title-category', $fonts),
				'thumb-hover-title' => get_thumb_hover_options('title', $fonts),	
				'thumb-hover-category' => get_thumb_hover_options('category', $fonts),
			),
		),
	),

	// -----------------------------------------
	// transitions
	// -----------------------------------------

	'transitions' => array(
		'tabs' => array(
			'options' => array(
				'preview-transition' => array(
					'title' => 'Preview',
					'hide-title'	=> true,
					'break'	=> '1',
					'preview' => array(
						'title'				=> 'Preview',
						'hide-title'		=> true,
						'size'				=> 'span4',
						'data-input-type'	=> 'button',
						'button-title'		=> 'Preview Transition',
						'class'				=> 'admin-listen-handler semplice-button',
						'data-handler'  	=> 'transitions',
					),
				),
				'background' => array(
					'title' => 'Browser Background Color',
					'break'	=> '1',
					'background-color' => array(
						'title'			=> 'Color',
						'hide-title' 	=> true,
						'help'			=> 'The default browser background color is white (browser default). To avoid that you can see the default white in between some page transitions you can change the default browser background color here.',
						'size'			=> 'span4',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-picker'	=> 'transitions',
					),
				),
				'select_preset' => array(
					'title' => 'Transition Options',
					'break' => '1,2',
					'status' => array(
						'data-input-type' 			=> 'switch',
						'help'						=> 'Select \'Disabled\' to show no transitions at all. (except your content editor motions)',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Status',
						'size'		 				=> 'span4',
						'class'						=> 'admin-listen-handler',
						'data-handler'  			=> 'transitions',
						'data-visibility-switch' 	=> true,
						'data-visibility-values' 	=> 'enabled,disabled',
						'data-visibility-prefix'	=> 'ov-status',
						'default' 	 				=> 'disabled',
						'switch-values' => array(
							'enabled'	 		=> 'Enabled',
							'disabled'  		=> 'Disabled',
						),
					),
					'preset' => array(
						'title'				=> 'Preset',
						'size'				=> 'span4',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'transitions',
						'style-class'		=> 'ov-status-enabled',
						'select-box-values' => array(
							'fade'			=> 'Fade',
							'rightToLeft'	=> 'Right to Left',
							'leftToRight'	=> 'Left to Right',
							'topToBottom'	=> 'Top to Bottom',
							'bottomToTop'	=> 'Bottom to Top',
						),
					),
				),
				'out_transition' => array(
					'title' 		=> 'Content Out Transition',
					'break' 		=> '2',
					'style-class'	=> 'ov-status-enabled',
					'duration_out' => array(
						'title'				=> 'Duration',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'transitions',
						'default'			=> 800,
						'min'				=> 0,
						'max'				=> 9999,
						'data-divider'		=> 1000,
						'data-range-slider' => 'transitions',
					),
					'easing_out' => array(
						'title'				=> 'Easing',
						'size'				=> 'span3',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'transitions',
						'select-box-values' => $easings,
					),
				),
				'in_transition' => array(
					'title' 		=> 'Content in Transition',
					'break'		 	=> '2',
					'style-class'	=> 'ov-status-enabled',
					'duration_in' => array(
						'title'				=> 'Duration',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'transitions',
						'default'			=> 800,
						'min'				=> 0,
						'max'				=> 9999,
						'data-divider'		=> 1000,
						'data-range-slider' => 'transitions',
					),
					'easing_in' => array(
						'title'				=> 'Easing',
						'size'				=> 'span3',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'transitions',
						'select-box-values' => $easings,
					),
				),
			),
			'scroll_reveal' => array(
				'options' => array(
					'title' => 'Options',
					'break' => '2,2,2,1',
					'hide-title' => true,
					'sr_viewFactor' => array(
						'title'				=> 'View factor (%)',
						'help'				=> 'Change when an element is considered in the viewport. Once an element is in the viewport of your browser it gets faded in. Default is 20%',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'transitions',
						'default'			=> 20,
						'min'				=> 0,
						'max'				=> 100,
						'data-divider'		=> 100,
						'data-range-slider' => 'transitions',
					),
					'sr_distance' => array(
						'title'				=> 'Distance',
						'help'				=> 'Define the distance the content should slide up while the \'reveal\' transitions runs.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'transitions',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 9999,
						'data-range-slider' => 'transitions',
					),
					'sr_easing' => array(
						'title'				=> 'Easing',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'transitions',
						'default'			=> 'ease-out',
						'select-box-values' => array(
							'ease-out'		=> 'ease-out',
							'ease'			=> 'ease',
							'linear'		=> 'linear',
							'ease-in'		=> 'ease-in',
							'ease-in-out'   => 'ease-in-out',
						),
					),
					'sr_duration' => array(
						'title'				=> 'Duration',
						'help'				=> 'Define the duration of your \'reveal\' transition',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'transitions',
						'default'			=> 700,
						'min'				=> 0,
						'max'				=> 9999,
						'data-range-slider' => 'transitions',
					),
					'sr_opacity' => array(
						'title'				=> 'Opactiy',
						'help'				=> 'Define starting opacity of your content before the \'reveal\' transition starts. Example: 80% means that the opacity of your content will fade from 80% to 100% while the duration of the transition.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'transitions',
						'default'			=> 0,
						'min'				=> 0,
						'max'				=> 100,
						'data-divider'		=> 100,
						'data-range-slider' => 'transitions',
					),
					'sr_scale' => array(
						'title'				=> 'Scale',
						'help'				=> 'Define starting scale of your content before the \'reveal\' transition starts. Example: 80% means that your content will get scaled from 80% to 100% while the duration of the transition.',
						'size'				=> 'span2',
						'offset'			=> false,
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'transitions',
						'default'			=> 100,
						'min'				=> 0,
						'max'				=> 100,
						'data-divider'		=> 100,
						'data-range-slider' => 'transitions',
					),
				),
			),
		),
	),

	// -----------------------------------------
	// blog
	// -----------------------------------------

	'blog' => array(
		'tabs' => array(
			'basic' => array(
				'blog-options' => array(
					'title' => 'General',
					'break'	=> '2,2',
					'blog_bg_color' => array(
						'title'			=> 'Background',
						'data-css-attribute' => 'background-color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '#content-holder',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_divider_color' => array(
						'title'			=> 'Divider',
						'data-css-attribute' => 'background-color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '.post-divider',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_width' => array(
						'title'				=> 'Width',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'default'			=> '8',
						'select-box-values' => array(
							'6'				=> '6 Columns',
							'7'				=> '7 Columns',
							'8'				=> '8 Columns',
							'9'				=> '9 Columns',
							'10'			=> '10 Columns',
							'11'			=> '11 Columns',
							'12'			=> '12 Columns',
						),
					),
					'blog_alignment' => array(
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Alignment',
						'size'		 				=> 'span2',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'blog',
						'default' 	 				=> 'center',
						'switch-values' => array(
							'center'  	=> 'Center',
							'left'	 	=> 'Left',
						),
					),
				),
				'head-meta-options' => array(
					'title' => 'Post Title Meta',
					'break'	=> '2,3',
					'blog_head_meta_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.post-heading p a',
						'select-box-values' => $fonts,
					),
					'blog_head_meta_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'blog',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.post-heading p a',
						'data-has-unit'		=> true,
						'default'			=> 18,
						'min'				=> 0,
						'max'				=> 9999,
						'data-range-slider' => 'blog',
					),
					'blog_head_meta_alignment' => array(
						'title'				=> 'Alignment',
						'data-css-attribute'=> 'text-align',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.post-heading p',
						'default'			=> 'left',
						'select-box-values' => array(
							'left'	=> 'Left',
							'center'=> 'Center',
							'right' => 'Right',
						),
					),
					'blog_head_meta_color' => array(
						'title'			=> 'Link',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.post-heading p a, .post-heading p',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_head_meta_mouseover_color' => array(
						'title'			=> 'Hover',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'title-options' => array(
					'title' => 'Post Title',
					'help'	=> 'To change the title font size, font family etc. please go to \'Customize -> Typography\'',
					'break'	=> '3',
					'blog_title_alignment' => array(
						'title'				=> 'Alignment',
						'data-css-attribute'=> 'text-align',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.post-heading h2',
						'default'			=> 'left',
						'select-box-values' => array(
							'left'	=> 'Left',
							'center'=> 'Center',
							'right' => 'Right',
						),
					),
					'blog_title_color' => array(
						'title'			=> 'Link',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.post-heading h2 a',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_title_mouseover_color' => array(
						'title'			=> 'Hover',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'content-options' => array(
					'title' => 'Post Content',
					'break'	=> '3',
					'help'	=> 'To change the content font size, font family etc. please go to \'Customize -> Typography\'',
					'blog_text_color' => array(
						'title'			=> 'Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.post-content',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_link_color' => array(
						'title'			=> 'Link',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.post-content a',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_mouseover_color' => array(
						'title'			=> 'Hover',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'meta-options' => array(
					'title' => 'Post Meta',
					'break'	=> '2,2,2',
					'blog_meta_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.post-meta p',
						'select-box-values' => $fonts,
					),
					'blog_meta_font_size' => array(
						'title'				=> 'Font size',
						'size'				=> 'span2',
						'data-input-type' 	=> 'range-slider',
						'class'				=> 'admin-listen-handler',
						'data-handler'		=> 'blog',
						'data-css-attribute'=> 'font-size',
						'data-target'		=> '.post-meta *',
						'data-has-unit'		=> true,
						'default'			=> 18,
						'min'				=> 0,
						'max'				=> 9999,
						'data-range-slider' => 'blog',
					),
					'blog_meta_alignment' => array(
						'title'				=> 'Alignment',
						'data-css-attribute'=> 'text-align',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.post-meta *',
						'default'			=> 'left',
						'select-box-values' => array(
							'left'	=> 'Left',
							'center'=> 'Center',
							'right' => 'Right',
						),
					),
					'blog_meta_color' => array(
						'title'			=> 'Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '.post-meta',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_meta_link_color' => array(
						'title'			=> 'Link',
						'data-css-attribute' => 'color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '.post-meta a',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'blog_meta_mouseover_color' => array(
						'title'			=> 'Hover',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
			),
			'advanced' => array(
				'featured-options' => array(
					'title' => 'Featured Image',
					'break'	=> '2',
					'blog_featured_width' => array(
						'title'				=> 'Width',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-box',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'default'			=> '12',
						'select-box-values' => array(
							'6'				=> '6 Columns',
							'7'				=> '7 Columns',
							'8'				=> '8 Columns',
							'9'				=> '9 Columns',
							'10'			=> '10 Columns',
							'11'			=> '11 Columns',
							'12'			=> '12 Columns',
							'fullscreen'	=> 'Fullscreen',
						),
					),
					'blog_featured_preview' => array(
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Preview Visibility',
						'size'		 				=> 'span2',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'blog',
						'default' 	 				=> 'visible',
						'switch-values' => array(
							'visible'	=> 'Visible',
							'hidden'  	=> 'Hidden',
						),
					),
				),
				'sr-options' => array(
					'title' => 'Scroll Reveal',
					'help'  => 'You can customize the \'Scroll Reveal\' options in \'Customize -> Transitions\'',
					'break'	=> '1',
					'blog_scroll_reveal' => array(
						'data-input-type' 	=> 'switch',
						'switch-type'		=> 'twoway',
						'title'		 		=> 'Status',
						'size'				=> 'span4',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'default'			=> 'enabled',
						'switch-values' => array(
							'enabled'	=> 'Enabled',
							'disabled'  => 'Disabled',
						),
					),
				),
				'visibility-options' => array(
					'title' => 'Visibility Options',
					'break'	=> '2',
					'blog_visibility_category' => array(
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Meta Published',
						'size'		 				=> 'span2',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'blog',
						'default' 	 				=> 'visible',
						'data-target'				=> '.category-meta',
						'switch-values' => array(
							'visible'	=> 'Visible',
							'hidden'  	=> 'Hidden',
						),
					),
					'blog_visibility_tags' => array(
						'data-input-type' 			=> 'switch',
						'switch-type'				=> 'twoway',
						'title'		 				=> 'Meta Tags',
						'size'		 				=> 'span2',
						'class'						=> 'admin-listen-handler',
						'data-handler'				=> 'blog',
						'default' 	 				=> 'visible',
						'data-target'				=> '.tags-meta',
						'switch-values' => array(
							'visible'	=> 'Visible',
							'hidden'  	=> 'Hidden',
						),
					),
				),
				'share_options' => get_share_module_options($fonts, true),
			),
			'comments-options' => array(
				'comments-background' => array(
					'title' => 'Background Color',
					'break'	=> '1',
					'hide-title' => true,
					'comment_bg_color' => array(
						'title'			=> 'Background Color',
						'data-css-attribute' => 'background-color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '#comments',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'title-options' => array(
					'title' => 'Title',
					'break'	=> '2',
					'comment_title_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.comments-title',
						'select-box-values' => $fonts,
					),
					'comment_title_color' => array(
						'title'			=> 'Title Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '.comments-title',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'author-options' => array(
					'title' => 'Author',
					'break'	=> '3',
					'comment_author_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.comment-author cite',
						'select-box-values' => $fonts,
					),
					'comment_author_color' => array(
						'title'			=> 'Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.comment-author cite, .comment-author cite a',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'comment_author_mouseover_color' => array(
						'title'			=> 'Hover',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'date-options' => array(
					'title' => 'Date',
					'break'	=> '3',
					'comment_date_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.comment-meta a',
						'select-box-values' => $fonts,
					),
					'comment_date_color' => array(
						'title'			=> 'Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.comment-meta a',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'comment_date_mouseover_color' => array(
						'title'			=> 'Hover',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'content-options' => array(
					'title' => 'Comment',
					'break'	=> '3',
					'comment_content_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.comment p',
						'select-box-values' => $fonts,
					),
					'comment_content_color' => array(
						'title'			=> 'Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.comment p',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'comment_content_divider_color' => array(
						'title'			=> 'Divider',
						'data-css-attribute' => 'border-color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.comment, .comment .depth-2, .comment .depth-3',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'reply-button-options' => array(
					'title' => 'Reply Button',
					'break'	=> '3',
					'comment_reply_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '.comment-reply-link, #cancel-comment-reply-link',
						'select-box-values' => $fonts,
					),
					'comment_reply_color' => array(
						'title'			=> 'Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.comment-reply-link, #cancel-comment-reply-link',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'comment_reply_border_color' => array(
						'title'			=> 'Border',
						'data-css-attribute' => 'border-color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '.comment-reply-link, #cancel-comment-reply-link',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'respond-options' => array(
					'title' => 'Respond Title',
					'break'	=> '2',
					'comment_respond_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '#reply-title, #reply-title a',
						'select-box-values' => $fonts,
					),
					'comment_respond_color' => array(
						'title'			=> 'Title Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span2',
						'data-input-type'	=> 'color',
						'data-target'	=> '#reply-title, #reply-title a',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
				'form-options' => array(
					'title' => 'Form Options',
					'break'	=> '1,3',
					'comment_form_bg_color' => array(
						'title'			=> 'Background Color',
						'data-css-attribute' => 'background-color',
						'size'			=> 'span4',
						'data-input-type'	=> 'color',
						'data-target'	=> '#commentform input, #commentform submit, #commentform textarea',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'comment_form_font_family' => array(
						'title'				=> 'Font Family',
						'size'				=> 'span2',
						'data-input-type'	=> 'select-fonts',
						'class'				=> 'admin-listen-handler',
						'data-handler'  	=> 'blog',
						'data-target'		=> '#commentform input, #commentform submit, #commentform textarea',
						'select-box-values' => $fonts,
					),
					'comment_form_color' => array(
						'title'			=> 'Color',
						'data-css-attribute' => 'color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '#commentform input, #commentform submit, #commentform textarea, ::-webkit-input-placeholder',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
					'comment_form_border_color' => array(
						'title'			=> 'Border',
						'data-css-attribute' => 'border-color',
						'size'			=> 'span1',
						'data-input-type'	=> 'color',
						'data-target'	=> '#commentform input, #commentform submit, #commentform textarea',
						'default'		=> 'transparent',
						'class'			=> 'color-picker admin-listen-handler',
						'data-handler'  => 'colorPicker',
						'data-has-unit'	=> false,
						'data-picker'   => 'blog',
					),
				),
			),
		),
	),

	// -----------------------------------------
	// advanced
	// -----------------------------------------

	'advanced' => array(
		'text' => array(
			'title'	 		=> 'Text Colors',
			'description' 	=> 'Define the basic text colors for your paragraphs.',
			'text_color' => array(
				'title'			=> 'Text Color',
				'size'			=> 'span1',
				'data-input-type'	=> 'color',
				'default'		=> '#000000',
				'class'			=> 'color-picker admin-listen-handler',
				'data-handler'  => 'colorPicker',
				'data-picker'	=> 'advanced',
			),
			'link_color' => array(
				'title'			=> 'Link Color',
				'size'			=> 'span1',
				'data-input-type'	=> 'color',
				'default'		=> '#1573dd',
				'class'			=> 'color-picker admin-listen-handler',
				'data-handler'  => 'colorPicker',
				'data-picker'	=> 'advanced',
			),
			'mouseover_color' => array(
				'title'			=> 'Hover Color',
				'size'			=> 'span1',
				'data-input-type'	=> 'color',
				'default'		=> '#000000',
				'class'			=> 'color-picker admin-listen-handler',
				'data-handler'  => 'colorPicker',
				'data-picker'	=> 'advanced',
			),
		),
		'progress-bar' => array(
			'title'	 		=> 'Loader Bar Color',
			'description' 	=> 'Define the color of your \'Loader Bar\'',
			'progress_bar' => array(
				'title'			=> 'Progress Bar Color',
				'hide-title'	=> true,
				'size'			=> 'span2',
				'data-input-type'	=> 'color',
				'default'		=> 'transparent',
				'class'			=> 'color-picker admin-listen-handler',
				'data-handler'  => 'colorPicker',
				'data-picker'	=> 'advanced',
			),
		),
		'back-to-top' => array(
			'title'	 		=> 'Back To Top Arrow Color',
			'description' 	=> 'Define the color of your \'Back to top\' arrow.',
			'top_arrow_color' => array(
				'title'			=> 'Back To Top Arrow Color',
				'hide-title'	=> true,
				'size'			=> 'span2',
				'data-input-type'	=> 'color',
				'default'		=> 'transparent',
				'class'			=> 'color-picker admin-listen-handler',
				'data-handler'  => 'colorPicker',
				'data-picker'	=> 'advanced',
			),
		),
		'global-footer' => array(
			'title'	 		=> 'Global Footer',
			'description' 	=> 'Define your global footer here. To define an individual footer for a page or project please do this in the post settings.<br /><br />Note: If your footer is not listed here, please make sure it\'s published already.',
			'global_footer' => array(
				'title'				 => 'Global Footer',
				'hide-title'		 => true,
				'size'				 => 'span2',
				'data-input-type'    => 'select-box',
				'class'			  	 => 'admin-listen-handler',
				'data-handler'       => 'advanced',
				'default'			 => '1',
				'data-settings-type' => 'general',
				'select-box-values' => semplice_get_post_dropdown('footer'),
			),
		),
		'password_protected' => array(
			'title' => 'Password Protected Pages',
			'description' 	=> 'Define the font and border color (both for input field and submit button) of your password protected pages here. To go more into detail or change it for individual pages please use custom css. Here you can find a <a href="https://pastebin.com/wa3fmkS3" target="_blank">snippet</a> to start with.',
			'password_color' => array(
				'title'				=> 'Font Color',
				'size'				=> 'span2',
				'data-input-type'	=> 'color',
				'default'			=> 'transparent',
				'class'				=> 'color-picker admin-listen-handler',
				'data-picker'		=> 'advanced',
				'data-handler'  	=> 'colorPicker',
			),
			'password_border' => array(
				'title'				=> 'Border Color',
				'size'				=> 'span2',
				'data-input-type'	=> 'color',
				'default'			=> 'transparent',
				'class'				=> 'color-picker admin-listen-handler',
				'data-picker'		=> 'advanced',
				'data-handler'  	=> 'colorPicker',
			),
		),
		'motion-tab' => array(
			'title'	 		=> 'Unlock Editor Motion Options',
			'description' 	=> 'Enable this option to activate the "Motion" feature. After enabling you will find motions in your edit popup in the content editor. See how it works <a href="https://vimeo.com/223057583/fe7b10f522" target="_blank">here</a>.',
			'motion_tab' => array(
				'data-input-type' 	=> 'switch',
				'switch-type'		=> 'twoway',
				'title'				=> 'Motion Options',
				'hide-title'		=> true,
				'size'				=> 'span4',
				'class'				=> 'admin-listen-handler',
				'data-handler'  	=> 'advanced',
				'default' 	 		=> 'disabled',
				'switch-values' => array(
					'disabled'	 => 'Disabled',
					'enabled' 	 => 'Enabled',
				),
			),
		),
		'custom-css' => array(
			'title' 		=> 'Custom CSS',
			'description' 	=> 'Choose the custom css you want to edit from the select box and hit \'Edit Custom CSS\'',
			'custom_css_switch' => array(
				'title'				=> 'Custom CSS Switch',
				'hide-title'		=> true,
				'size'				=> 'span2',
				'data-input-type'	=> 'select-box',
				'class'				=> 'admin-listen-handler',
				'data-handler'  	=> 'advanced',
				'select-box-values' => array(
					'global'		=> 'Global',
					'xl'			=> 'Desktop Wide',
					'lg'			=> 'Desktop',
					'md'			=> 'Tablet Wide',
					'sm'			=> 'Tablet Portrait',
					'xs'			=> 'Mobile',
				),
			),
			'custom_css' 	=> array(
				'title'				=> 'Edit CSS Code',
				'hide-title'		=> true,
				'size'				=> 'span2',
				'help'				=> '',
				'data-input-type'	=> 'codemirror',
				'placeholder'		=> '',
				'default'			=> '',
				'button-title'		=> 'Edit Custom css',
				'class'				=> 'semplice-button codemirror white-button admin-click-handler',
				'data-handler'		=> 'codemirror',
			),
		),
		'custom-js' => array(
			'title' 		=> 'Custom Javascript',
			'description' 	=> 'This custom javascript gets applied globally to all pages and projects.<br /><br />Note: Please start right away with your javascript code without using any html tags like (< script >).<br /><br />Example: alert("Hello World");',
			'custom_js' 	=> array(
				'title'				=> 'Edit CSS Code',
				'hide-title'		=> true,
				'size'				=> 'span2',
				'offset'			=> 'offset2',
				'help'				=> '',
				'data-input-type'	=> 'codemirror',
				'placeholder'		=> '',
				'default'			=> '',
				'button-title'		=> 'Edit Javascript',
				'class'				=> 'semplice-button codemirror white-button admin-click-handler',
				'data-handler'		=> 'codemirror',
			),
		),
	),
);

?>